apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ireguero-ch-tls
spec:
  secretName: ireguero-ch
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ireguero.ch
  dnsNames:
    - ireguero.ch
    - www.ireguero.ch
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ireguero.ch
          - www.ireguero.ch
